services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  springboot-app:
    build: .
    container_name: springboot-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://root:examplepassword@mongodb:27017/shorturls?authSource=admin
      - SPRING_CACHE_HOST=redis
      - REDIS_TTL=600000
    depends_on:
      - mongodb
      - redis

volumes:
  mongo-data:
  redis-data: