services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  springboot-app:
    build: .
    container_name: springboot-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SPRING_CACHE_HOST=${SPRING_CACHE_HOST}
      - REDIS_TTL=${REDIS_TTL}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_S3_REGION=${AWS_S3_REGION}
    depends_on:
      - mongodb
      - redis

volumes:
  mongo-data:
  redis-data: